//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace NAVExtension.generaljournal {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GeneralJournalService_Binding", Namespace="urn:microsoft-dynamics-schemas/page/generaljournalservice")]
    public partial class GeneralJournalService_Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ReadByRecIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadMultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsUpdatedOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRecIdFromKeyOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateMultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateMultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public GeneralJournalService_Service() {
            this.Url = global::NAVExtension.Properties.Settings.Default.NAVExtension_generaljournal_GeneralJournalService_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ReadByRecIdCompletedEventHandler ReadByRecIdCompleted;
        
        /// <remarks/>
        public event ReadMultipleCompletedEventHandler ReadMultipleCompleted;
        
        /// <remarks/>
        public event IsUpdatedCompletedEventHandler IsUpdatedCompleted;
        
        /// <remarks/>
        public event GetRecIdFromKeyCompletedEventHandler GetRecIdFromKeyCompleted;
        
        /// <remarks/>
        public event CreateCompletedEventHandler CreateCompleted;
        
        /// <remarks/>
        public event CreateMultipleCompletedEventHandler CreateMultipleCompleted;
        
        /// <remarks/>
        public event UpdateCompletedEventHandler UpdateCompleted;
        
        /// <remarks/>
        public event UpdateMultipleCompletedEventHandler UpdateMultipleCompleted;
        
        /// <remarks/>
        public event DeleteCompletedEventHandler DeleteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/generaljournalservice:ReadByRecId", RequestNamespace="urn:microsoft-dynamics-schemas/page/generaljournalservice", ResponseElementName="ReadByRecId_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/generaljournalservice", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GeneralJournalService")]
        public GeneralJournalService ReadByRecId(string CurrentJnlBatchName, string recId) {
            object[] results = this.Invoke("ReadByRecId", new object[] {
                        CurrentJnlBatchName,
                        recId});
            return ((GeneralJournalService)(results[0]));
        }
        
        /// <remarks/>
        public void ReadByRecIdAsync(string CurrentJnlBatchName, string recId) {
            this.ReadByRecIdAsync(CurrentJnlBatchName, recId, null);
        }
        
        /// <remarks/>
        public void ReadByRecIdAsync(string CurrentJnlBatchName, string recId, object userState) {
            if ((this.ReadByRecIdOperationCompleted == null)) {
                this.ReadByRecIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadByRecIdOperationCompleted);
            }
            this.InvokeAsync("ReadByRecId", new object[] {
                        CurrentJnlBatchName,
                        recId}, this.ReadByRecIdOperationCompleted, userState);
        }
        
        private void OnReadByRecIdOperationCompleted(object arg) {
            if ((this.ReadByRecIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadByRecIdCompleted(this, new ReadByRecIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/generaljournalservice:ReadMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/generaljournalservice", ResponseElementName="ReadMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/generaljournalservice", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("ReadMultiple_Result")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public GeneralJournalService[] ReadMultiple(string CurrentJnlBatchName, [System.Xml.Serialization.XmlElementAttribute("filter")] GeneralJournalService_Filter[] filter, string bookmarkKey, int setSize) {
            object[] results = this.Invoke("ReadMultiple", new object[] {
                        CurrentJnlBatchName,
                        filter,
                        bookmarkKey,
                        setSize});
            return ((GeneralJournalService[])(results[0]));
        }
        
        /// <remarks/>
        public void ReadMultipleAsync(string CurrentJnlBatchName, GeneralJournalService_Filter[] filter, string bookmarkKey, int setSize) {
            this.ReadMultipleAsync(CurrentJnlBatchName, filter, bookmarkKey, setSize, null);
        }
        
        /// <remarks/>
        public void ReadMultipleAsync(string CurrentJnlBatchName, GeneralJournalService_Filter[] filter, string bookmarkKey, int setSize, object userState) {
            if ((this.ReadMultipleOperationCompleted == null)) {
                this.ReadMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadMultipleOperationCompleted);
            }
            this.InvokeAsync("ReadMultiple", new object[] {
                        CurrentJnlBatchName,
                        filter,
                        bookmarkKey,
                        setSize}, this.ReadMultipleOperationCompleted, userState);
        }
        
        private void OnReadMultipleOperationCompleted(object arg) {
            if ((this.ReadMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadMultipleCompleted(this, new ReadMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/generaljournalservice:IsUpdated", RequestNamespace="urn:microsoft-dynamics-schemas/page/generaljournalservice", ResponseElementName="IsUpdated_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/generaljournalservice", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("IsUpdated_Result")]
        public bool IsUpdated(string Key) {
            object[] results = this.Invoke("IsUpdated", new object[] {
                        Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsUpdatedAsync(string Key) {
            this.IsUpdatedAsync(Key, null);
        }
        
        /// <remarks/>
        public void IsUpdatedAsync(string Key, object userState) {
            if ((this.IsUpdatedOperationCompleted == null)) {
                this.IsUpdatedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsUpdatedOperationCompleted);
            }
            this.InvokeAsync("IsUpdated", new object[] {
                        Key}, this.IsUpdatedOperationCompleted, userState);
        }
        
        private void OnIsUpdatedOperationCompleted(object arg) {
            if ((this.IsUpdatedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsUpdatedCompleted(this, new IsUpdatedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/generaljournalservice:GetRecIdFromKey", RequestNamespace="urn:microsoft-dynamics-schemas/page/generaljournalservice", ResponseElementName="GetRecIdFromKey_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/generaljournalservice", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetRecIdFromKey_Result")]
        public string GetRecIdFromKey(string Key) {
            object[] results = this.Invoke("GetRecIdFromKey", new object[] {
                        Key});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetRecIdFromKeyAsync(string Key) {
            this.GetRecIdFromKeyAsync(Key, null);
        }
        
        /// <remarks/>
        public void GetRecIdFromKeyAsync(string Key, object userState) {
            if ((this.GetRecIdFromKeyOperationCompleted == null)) {
                this.GetRecIdFromKeyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRecIdFromKeyOperationCompleted);
            }
            this.InvokeAsync("GetRecIdFromKey", new object[] {
                        Key}, this.GetRecIdFromKeyOperationCompleted, userState);
        }
        
        private void OnGetRecIdFromKeyOperationCompleted(object arg) {
            if ((this.GetRecIdFromKeyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRecIdFromKeyCompleted(this, new GetRecIdFromKeyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/generaljournalservice:Create", RequestNamespace="urn:microsoft-dynamics-schemas/page/generaljournalservice", ResponseElementName="Create_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/generaljournalservice", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Create(string CurrentJnlBatchName, ref GeneralJournalService GeneralJournalService) {
            object[] results = this.Invoke("Create", new object[] {
                        CurrentJnlBatchName,
                        GeneralJournalService});
            GeneralJournalService = ((GeneralJournalService)(results[0]));
        }
        
        /// <remarks/>
        public void CreateAsync(string CurrentJnlBatchName, GeneralJournalService GeneralJournalService) {
            this.CreateAsync(CurrentJnlBatchName, GeneralJournalService, null);
        }
        
        /// <remarks/>
        public void CreateAsync(string CurrentJnlBatchName, GeneralJournalService GeneralJournalService, object userState) {
            if ((this.CreateOperationCompleted == null)) {
                this.CreateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateOperationCompleted);
            }
            this.InvokeAsync("Create", new object[] {
                        CurrentJnlBatchName,
                        GeneralJournalService}, this.CreateOperationCompleted, userState);
        }
        
        private void OnCreateOperationCompleted(object arg) {
            if ((this.CreateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateCompleted(this, new CreateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/generaljournalservice:CreateMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/generaljournalservice", ResponseElementName="CreateMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/generaljournalservice", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateMultiple(string CurrentJnlBatchName, [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] ref GeneralJournalService[] GeneralJournalService_List) {
            object[] results = this.Invoke("CreateMultiple", new object[] {
                        CurrentJnlBatchName,
                        GeneralJournalService_List});
            GeneralJournalService_List = ((GeneralJournalService[])(results[0]));
        }
        
        /// <remarks/>
        public void CreateMultipleAsync(string CurrentJnlBatchName, GeneralJournalService[] GeneralJournalService_List) {
            this.CreateMultipleAsync(CurrentJnlBatchName, GeneralJournalService_List, null);
        }
        
        /// <remarks/>
        public void CreateMultipleAsync(string CurrentJnlBatchName, GeneralJournalService[] GeneralJournalService_List, object userState) {
            if ((this.CreateMultipleOperationCompleted == null)) {
                this.CreateMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateMultipleOperationCompleted);
            }
            this.InvokeAsync("CreateMultiple", new object[] {
                        CurrentJnlBatchName,
                        GeneralJournalService_List}, this.CreateMultipleOperationCompleted, userState);
        }
        
        private void OnCreateMultipleOperationCompleted(object arg) {
            if ((this.CreateMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateMultipleCompleted(this, new CreateMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/generaljournalservice:Update", RequestNamespace="urn:microsoft-dynamics-schemas/page/generaljournalservice", ResponseElementName="Update_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/generaljournalservice", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Update(string CurrentJnlBatchName, ref GeneralJournalService GeneralJournalService) {
            object[] results = this.Invoke("Update", new object[] {
                        CurrentJnlBatchName,
                        GeneralJournalService});
            GeneralJournalService = ((GeneralJournalService)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateAsync(string CurrentJnlBatchName, GeneralJournalService GeneralJournalService) {
            this.UpdateAsync(CurrentJnlBatchName, GeneralJournalService, null);
        }
        
        /// <remarks/>
        public void UpdateAsync(string CurrentJnlBatchName, GeneralJournalService GeneralJournalService, object userState) {
            if ((this.UpdateOperationCompleted == null)) {
                this.UpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOperationCompleted);
            }
            this.InvokeAsync("Update", new object[] {
                        CurrentJnlBatchName,
                        GeneralJournalService}, this.UpdateOperationCompleted, userState);
        }
        
        private void OnUpdateOperationCompleted(object arg) {
            if ((this.UpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCompleted(this, new UpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/generaljournalservice:UpdateMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/generaljournalservice", ResponseElementName="UpdateMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/generaljournalservice", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateMultiple(string CurrentJnlBatchName, [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] ref GeneralJournalService[] GeneralJournalService_List) {
            object[] results = this.Invoke("UpdateMultiple", new object[] {
                        CurrentJnlBatchName,
                        GeneralJournalService_List});
            GeneralJournalService_List = ((GeneralJournalService[])(results[0]));
        }
        
        /// <remarks/>
        public void UpdateMultipleAsync(string CurrentJnlBatchName, GeneralJournalService[] GeneralJournalService_List) {
            this.UpdateMultipleAsync(CurrentJnlBatchName, GeneralJournalService_List, null);
        }
        
        /// <remarks/>
        public void UpdateMultipleAsync(string CurrentJnlBatchName, GeneralJournalService[] GeneralJournalService_List, object userState) {
            if ((this.UpdateMultipleOperationCompleted == null)) {
                this.UpdateMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateMultipleOperationCompleted);
            }
            this.InvokeAsync("UpdateMultiple", new object[] {
                        CurrentJnlBatchName,
                        GeneralJournalService_List}, this.UpdateMultipleOperationCompleted, userState);
        }
        
        private void OnUpdateMultipleOperationCompleted(object arg) {
            if ((this.UpdateMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateMultipleCompleted(this, new UpdateMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/generaljournalservice:Delete", RequestNamespace="urn:microsoft-dynamics-schemas/page/generaljournalservice", ResponseElementName="Delete_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/generaljournalservice", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Delete_Result")]
        public bool Delete(string CurrentJnlBatchName, string Key) {
            object[] results = this.Invoke("Delete", new object[] {
                        CurrentJnlBatchName,
                        Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteAsync(string CurrentJnlBatchName, string Key) {
            this.DeleteAsync(CurrentJnlBatchName, Key, null);
        }
        
        /// <remarks/>
        public void DeleteAsync(string CurrentJnlBatchName, string Key, object userState) {
            if ((this.DeleteOperationCompleted == null)) {
                this.DeleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteOperationCompleted);
            }
            this.InvokeAsync("Delete", new object[] {
                        CurrentJnlBatchName,
                        Key}, this.DeleteOperationCompleted, userState);
        }
        
        private void OnDeleteOperationCompleted(object arg) {
            if ((this.DeleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteCompleted(this, new DeleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/generaljournalservice")]
    public partial class GeneralJournalService {
        
        private string keyField;
        
        private System.DateTime posting_DateField;
        
        private bool posting_DateFieldSpecified;
        
        private System.DateTime document_DateField;
        
        private bool document_DateFieldSpecified;
        
        private Document_Type document_TypeField;
        
        private bool document_TypeFieldSpecified;
        
        private string document_NoField;
        
        private int incoming_Document_Entry_NoField;
        
        private bool incoming_Document_Entry_NoFieldSpecified;
        
        private string external_Document_NoField;
        
        private string applies_to_Ext_Doc_NoField;
        
        private Account_Type account_TypeField;
        
        private bool account_TypeFieldSpecified;
        
        private string account_NoField;
        
        private string descriptionField;
        
        private string payer_InformationField;
        
        private string transaction_InformationField;
        
        private string business_Unit_CodeField;
        
        private string salespers_Purch_CodeField;
        
        private string campaign_NoField;
        
        private string currency_CodeField;
        
        private Gen_Posting_Type gen_Posting_TypeField;
        
        private bool gen_Posting_TypeFieldSpecified;
        
        private string gen_Bus_Posting_GroupField;
        
        private string gen_Prod_Posting_GroupField;
        
        private string vAT_Bus_Posting_GroupField;
        
        private string vAT_Prod_Posting_GroupField;
        
        private decimal quantityField;
        
        private bool quantityFieldSpecified;
        
        private decimal amountField;
        
        private bool amountFieldSpecified;
        
        private decimal debit_AmountField;
        
        private bool debit_AmountFieldSpecified;
        
        private decimal credit_AmountField;
        
        private bool credit_AmountFieldSpecified;
        
        private decimal vAT_AmountField;
        
        private bool vAT_AmountFieldSpecified;
        
        private decimal vAT_DifferenceField;
        
        private bool vAT_DifferenceFieldSpecified;
        
        private decimal bal_VAT_AmountField;
        
        private bool bal_VAT_AmountFieldSpecified;
        
        private decimal bal_VAT_DifferenceField;
        
        private bool bal_VAT_DifferenceFieldSpecified;
        
        private Bal_Account_Type bal_Account_TypeField;
        
        private bool bal_Account_TypeFieldSpecified;
        
        private string bal_Account_NoField;
        
        private Bal_Gen_Posting_Type bal_Gen_Posting_TypeField;
        
        private bool bal_Gen_Posting_TypeFieldSpecified;
        
        private string bal_Gen_Bus_Posting_GroupField;
        
        private string bal_Gen_Prod_Posting_GroupField;
        
        private string deferral_CodeField;
        
        private string bal_VAT_Bus_Posting_GroupField;
        
        private string bal_VAT_Prod_Posting_GroupField;
        
        private string bill_to_Pay_to_NoField;
        
        private string ship_to_Order_Address_CodeField;
        
        private string shortcut_Dimension_1_CodeField;
        
        private string shortcut_Dimension_2_CodeField;
        
        private string shortcutDimCode3Field;
        
        private string shortcutDimCode4Field;
        
        private string shortcutDimCode5Field;
        
        private string shortcutDimCode6Field;
        
        private string shortcutDimCode7Field;
        
        private string shortcutDimCode8Field;
        
        private string payment_Terms_CodeField;
        
        private bool applied_AutomaticallyField;
        
        private bool applied_AutomaticallyFieldSpecified;
        
        private bool appliedField;
        
        private bool appliedFieldSpecified;
        
        private Applies_to_Doc_Type applies_to_Doc_TypeField;
        
        private bool applies_to_Doc_TypeFieldSpecified;
        
        private string applies_to_Doc_NoField;
        
        private string applies_to_IDField;
        
        private string on_HoldField;
        
        private Bank_Payment_Type bank_Payment_TypeField;
        
        private bool bank_Payment_TypeFieldSpecified;
        
        private string reason_CodeField;
        
        private string commentField;
        
        private string direct_Debit_Mandate_IDField;
        
        private string accNameField;
        
        private string balAccNameField;
        
        private decimal balanceField;
        
        private bool balanceFieldSpecified;
        
        private decimal totalBalanceField;
        
        private bool totalBalanceFieldSpecified;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Posting_Date {
            get {
                return this.posting_DateField;
            }
            set {
                this.posting_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Posting_DateSpecified {
            get {
                return this.posting_DateFieldSpecified;
            }
            set {
                this.posting_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Document_Date {
            get {
                return this.document_DateField;
            }
            set {
                this.document_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Document_DateSpecified {
            get {
                return this.document_DateFieldSpecified;
            }
            set {
                this.document_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Document_Type Document_Type {
            get {
                return this.document_TypeField;
            }
            set {
                this.document_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Document_TypeSpecified {
            get {
                return this.document_TypeFieldSpecified;
            }
            set {
                this.document_TypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Document_No {
            get {
                return this.document_NoField;
            }
            set {
                this.document_NoField = value;
            }
        }
        
        /// <remarks/>
        public int Incoming_Document_Entry_No {
            get {
                return this.incoming_Document_Entry_NoField;
            }
            set {
                this.incoming_Document_Entry_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Incoming_Document_Entry_NoSpecified {
            get {
                return this.incoming_Document_Entry_NoFieldSpecified;
            }
            set {
                this.incoming_Document_Entry_NoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string External_Document_No {
            get {
                return this.external_Document_NoField;
            }
            set {
                this.external_Document_NoField = value;
            }
        }
        
        /// <remarks/>
        public string Applies_to_Ext_Doc_No {
            get {
                return this.applies_to_Ext_Doc_NoField;
            }
            set {
                this.applies_to_Ext_Doc_NoField = value;
            }
        }
        
        /// <remarks/>
        public Account_Type Account_Type {
            get {
                return this.account_TypeField;
            }
            set {
                this.account_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Account_TypeSpecified {
            get {
                return this.account_TypeFieldSpecified;
            }
            set {
                this.account_TypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Account_No {
            get {
                return this.account_NoField;
            }
            set {
                this.account_NoField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Payer_Information {
            get {
                return this.payer_InformationField;
            }
            set {
                this.payer_InformationField = value;
            }
        }
        
        /// <remarks/>
        public string Transaction_Information {
            get {
                return this.transaction_InformationField;
            }
            set {
                this.transaction_InformationField = value;
            }
        }
        
        /// <remarks/>
        public string Business_Unit_Code {
            get {
                return this.business_Unit_CodeField;
            }
            set {
                this.business_Unit_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Salespers_Purch_Code {
            get {
                return this.salespers_Purch_CodeField;
            }
            set {
                this.salespers_Purch_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Campaign_No {
            get {
                return this.campaign_NoField;
            }
            set {
                this.campaign_NoField = value;
            }
        }
        
        /// <remarks/>
        public string Currency_Code {
            get {
                return this.currency_CodeField;
            }
            set {
                this.currency_CodeField = value;
            }
        }
        
        /// <remarks/>
        public Gen_Posting_Type Gen_Posting_Type {
            get {
                return this.gen_Posting_TypeField;
            }
            set {
                this.gen_Posting_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Gen_Posting_TypeSpecified {
            get {
                return this.gen_Posting_TypeFieldSpecified;
            }
            set {
                this.gen_Posting_TypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Gen_Bus_Posting_Group {
            get {
                return this.gen_Bus_Posting_GroupField;
            }
            set {
                this.gen_Bus_Posting_GroupField = value;
            }
        }
        
        /// <remarks/>
        public string Gen_Prod_Posting_Group {
            get {
                return this.gen_Prod_Posting_GroupField;
            }
            set {
                this.gen_Prod_Posting_GroupField = value;
            }
        }
        
        /// <remarks/>
        public string VAT_Bus_Posting_Group {
            get {
                return this.vAT_Bus_Posting_GroupField;
            }
            set {
                this.vAT_Bus_Posting_GroupField = value;
            }
        }
        
        /// <remarks/>
        public string VAT_Prod_Posting_Group {
            get {
                return this.vAT_Prod_Posting_GroupField;
            }
            set {
                this.vAT_Prod_Posting_GroupField = value;
            }
        }
        
        /// <remarks/>
        public decimal Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QuantitySpecified {
            get {
                return this.quantityFieldSpecified;
            }
            set {
                this.quantityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AmountSpecified {
            get {
                return this.amountFieldSpecified;
            }
            set {
                this.amountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Debit_Amount {
            get {
                return this.debit_AmountField;
            }
            set {
                this.debit_AmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Debit_AmountSpecified {
            get {
                return this.debit_AmountFieldSpecified;
            }
            set {
                this.debit_AmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Credit_Amount {
            get {
                return this.credit_AmountField;
            }
            set {
                this.credit_AmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Credit_AmountSpecified {
            get {
                return this.credit_AmountFieldSpecified;
            }
            set {
                this.credit_AmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal VAT_Amount {
            get {
                return this.vAT_AmountField;
            }
            set {
                this.vAT_AmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VAT_AmountSpecified {
            get {
                return this.vAT_AmountFieldSpecified;
            }
            set {
                this.vAT_AmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal VAT_Difference {
            get {
                return this.vAT_DifferenceField;
            }
            set {
                this.vAT_DifferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VAT_DifferenceSpecified {
            get {
                return this.vAT_DifferenceFieldSpecified;
            }
            set {
                this.vAT_DifferenceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Bal_VAT_Amount {
            get {
                return this.bal_VAT_AmountField;
            }
            set {
                this.bal_VAT_AmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Bal_VAT_AmountSpecified {
            get {
                return this.bal_VAT_AmountFieldSpecified;
            }
            set {
                this.bal_VAT_AmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Bal_VAT_Difference {
            get {
                return this.bal_VAT_DifferenceField;
            }
            set {
                this.bal_VAT_DifferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Bal_VAT_DifferenceSpecified {
            get {
                return this.bal_VAT_DifferenceFieldSpecified;
            }
            set {
                this.bal_VAT_DifferenceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Bal_Account_Type Bal_Account_Type {
            get {
                return this.bal_Account_TypeField;
            }
            set {
                this.bal_Account_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Bal_Account_TypeSpecified {
            get {
                return this.bal_Account_TypeFieldSpecified;
            }
            set {
                this.bal_Account_TypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Bal_Account_No {
            get {
                return this.bal_Account_NoField;
            }
            set {
                this.bal_Account_NoField = value;
            }
        }
        
        /// <remarks/>
        public Bal_Gen_Posting_Type Bal_Gen_Posting_Type {
            get {
                return this.bal_Gen_Posting_TypeField;
            }
            set {
                this.bal_Gen_Posting_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Bal_Gen_Posting_TypeSpecified {
            get {
                return this.bal_Gen_Posting_TypeFieldSpecified;
            }
            set {
                this.bal_Gen_Posting_TypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Bal_Gen_Bus_Posting_Group {
            get {
                return this.bal_Gen_Bus_Posting_GroupField;
            }
            set {
                this.bal_Gen_Bus_Posting_GroupField = value;
            }
        }
        
        /// <remarks/>
        public string Bal_Gen_Prod_Posting_Group {
            get {
                return this.bal_Gen_Prod_Posting_GroupField;
            }
            set {
                this.bal_Gen_Prod_Posting_GroupField = value;
            }
        }
        
        /// <remarks/>
        public string Deferral_Code {
            get {
                return this.deferral_CodeField;
            }
            set {
                this.deferral_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Bal_VAT_Bus_Posting_Group {
            get {
                return this.bal_VAT_Bus_Posting_GroupField;
            }
            set {
                this.bal_VAT_Bus_Posting_GroupField = value;
            }
        }
        
        /// <remarks/>
        public string Bal_VAT_Prod_Posting_Group {
            get {
                return this.bal_VAT_Prod_Posting_GroupField;
            }
            set {
                this.bal_VAT_Prod_Posting_GroupField = value;
            }
        }
        
        /// <remarks/>
        public string Bill_to_Pay_to_No {
            get {
                return this.bill_to_Pay_to_NoField;
            }
            set {
                this.bill_to_Pay_to_NoField = value;
            }
        }
        
        /// <remarks/>
        public string Ship_to_Order_Address_Code {
            get {
                return this.ship_to_Order_Address_CodeField;
            }
            set {
                this.ship_to_Order_Address_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Shortcut_Dimension_1_Code {
            get {
                return this.shortcut_Dimension_1_CodeField;
            }
            set {
                this.shortcut_Dimension_1_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Shortcut_Dimension_2_Code {
            get {
                return this.shortcut_Dimension_2_CodeField;
            }
            set {
                this.shortcut_Dimension_2_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ShortcutDimCode[3]")]
        public string ShortcutDimCode3 {
            get {
                return this.shortcutDimCode3Field;
            }
            set {
                this.shortcutDimCode3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ShortcutDimCode[4]")]
        public string ShortcutDimCode4 {
            get {
                return this.shortcutDimCode4Field;
            }
            set {
                this.shortcutDimCode4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ShortcutDimCode[5]")]
        public string ShortcutDimCode5 {
            get {
                return this.shortcutDimCode5Field;
            }
            set {
                this.shortcutDimCode5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ShortcutDimCode[6]")]
        public string ShortcutDimCode6 {
            get {
                return this.shortcutDimCode6Field;
            }
            set {
                this.shortcutDimCode6Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ShortcutDimCode[7]")]
        public string ShortcutDimCode7 {
            get {
                return this.shortcutDimCode7Field;
            }
            set {
                this.shortcutDimCode7Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ShortcutDimCode[8]")]
        public string ShortcutDimCode8 {
            get {
                return this.shortcutDimCode8Field;
            }
            set {
                this.shortcutDimCode8Field = value;
            }
        }
        
        /// <remarks/>
        public string Payment_Terms_Code {
            get {
                return this.payment_Terms_CodeField;
            }
            set {
                this.payment_Terms_CodeField = value;
            }
        }
        
        /// <remarks/>
        public bool Applied_Automatically {
            get {
                return this.applied_AutomaticallyField;
            }
            set {
                this.applied_AutomaticallyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Applied_AutomaticallySpecified {
            get {
                return this.applied_AutomaticallyFieldSpecified;
            }
            set {
                this.applied_AutomaticallyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Applied {
            get {
                return this.appliedField;
            }
            set {
                this.appliedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AppliedSpecified {
            get {
                return this.appliedFieldSpecified;
            }
            set {
                this.appliedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Applies_to_Doc_Type Applies_to_Doc_Type {
            get {
                return this.applies_to_Doc_TypeField;
            }
            set {
                this.applies_to_Doc_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Applies_to_Doc_TypeSpecified {
            get {
                return this.applies_to_Doc_TypeFieldSpecified;
            }
            set {
                this.applies_to_Doc_TypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Applies_to_Doc_No {
            get {
                return this.applies_to_Doc_NoField;
            }
            set {
                this.applies_to_Doc_NoField = value;
            }
        }
        
        /// <remarks/>
        public string Applies_to_ID {
            get {
                return this.applies_to_IDField;
            }
            set {
                this.applies_to_IDField = value;
            }
        }
        
        /// <remarks/>
        public string On_Hold {
            get {
                return this.on_HoldField;
            }
            set {
                this.on_HoldField = value;
            }
        }
        
        /// <remarks/>
        public Bank_Payment_Type Bank_Payment_Type {
            get {
                return this.bank_Payment_TypeField;
            }
            set {
                this.bank_Payment_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Bank_Payment_TypeSpecified {
            get {
                return this.bank_Payment_TypeFieldSpecified;
            }
            set {
                this.bank_Payment_TypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Reason_Code {
            get {
                return this.reason_CodeField;
            }
            set {
                this.reason_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
            }
        }
        
        /// <remarks/>
        public string Direct_Debit_Mandate_ID {
            get {
                return this.direct_Debit_Mandate_IDField;
            }
            set {
                this.direct_Debit_Mandate_IDField = value;
            }
        }
        
        /// <remarks/>
        public string AccName {
            get {
                return this.accNameField;
            }
            set {
                this.accNameField = value;
            }
        }
        
        /// <remarks/>
        public string BalAccName {
            get {
                return this.balAccNameField;
            }
            set {
                this.balAccNameField = value;
            }
        }
        
        /// <remarks/>
        public decimal Balance {
            get {
                return this.balanceField;
            }
            set {
                this.balanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BalanceSpecified {
            get {
                return this.balanceFieldSpecified;
            }
            set {
                this.balanceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal TotalBalance {
            get {
                return this.totalBalanceField;
            }
            set {
                this.totalBalanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalBalanceSpecified {
            get {
                return this.totalBalanceFieldSpecified;
            }
            set {
                this.totalBalanceFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/generaljournalservice")]
    public enum Document_Type {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        Payment,
        
        /// <remarks/>
        Invoice,
        
        /// <remarks/>
        Credit_Memo,
        
        /// <remarks/>
        Finance_Charge_Memo,
        
        /// <remarks/>
        Reminder,
        
        /// <remarks/>
        Refund,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/generaljournalservice")]
    public enum Account_Type {
        
        /// <remarks/>
        G_L_Account,
        
        /// <remarks/>
        Customer,
        
        /// <remarks/>
        Vendor,
        
        /// <remarks/>
        Bank_Account,
        
        /// <remarks/>
        Fixed_Asset,
        
        /// <remarks/>
        IC_Partner,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/generaljournalservice")]
    public enum Gen_Posting_Type {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        Purchase,
        
        /// <remarks/>
        Sale,
        
        /// <remarks/>
        Settlement,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/generaljournalservice")]
    public enum Bal_Account_Type {
        
        /// <remarks/>
        G_L_Account,
        
        /// <remarks/>
        Customer,
        
        /// <remarks/>
        Vendor,
        
        /// <remarks/>
        Bank_Account,
        
        /// <remarks/>
        Fixed_Asset,
        
        /// <remarks/>
        IC_Partner,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/generaljournalservice")]
    public enum Bal_Gen_Posting_Type {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        Purchase,
        
        /// <remarks/>
        Sale,
        
        /// <remarks/>
        Settlement,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/generaljournalservice")]
    public enum Applies_to_Doc_Type {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        Payment,
        
        /// <remarks/>
        Invoice,
        
        /// <remarks/>
        Credit_Memo,
        
        /// <remarks/>
        Finance_Charge_Memo,
        
        /// <remarks/>
        Reminder,
        
        /// <remarks/>
        Refund,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/generaljournalservice")]
    public enum Bank_Payment_Type {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        Computer_Check,
        
        /// <remarks/>
        Manual_Check,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/generaljournalservice")]
    public partial class GeneralJournalService_Filter {
        
        private GeneralJournalService_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        public GeneralJournalService_Fields Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        public string Criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/generaljournalservice")]
    public enum GeneralJournalService_Fields {
        
        /// <remarks/>
        Posting_Date,
        
        /// <remarks/>
        Document_Date,
        
        /// <remarks/>
        Document_Type,
        
        /// <remarks/>
        Document_No,
        
        /// <remarks/>
        Incoming_Document_Entry_No,
        
        /// <remarks/>
        External_Document_No,
        
        /// <remarks/>
        Applies_to_Ext_Doc_No,
        
        /// <remarks/>
        Account_Type,
        
        /// <remarks/>
        Account_No,
        
        /// <remarks/>
        Description,
        
        /// <remarks/>
        Payer_Information,
        
        /// <remarks/>
        Transaction_Information,
        
        /// <remarks/>
        Business_Unit_Code,
        
        /// <remarks/>
        Salespers_Purch_Code,
        
        /// <remarks/>
        Campaign_No,
        
        /// <remarks/>
        Currency_Code,
        
        /// <remarks/>
        Gen_Posting_Type,
        
        /// <remarks/>
        Gen_Bus_Posting_Group,
        
        /// <remarks/>
        Gen_Prod_Posting_Group,
        
        /// <remarks/>
        VAT_Bus_Posting_Group,
        
        /// <remarks/>
        VAT_Prod_Posting_Group,
        
        /// <remarks/>
        Quantity,
        
        /// <remarks/>
        Amount,
        
        /// <remarks/>
        Debit_Amount,
        
        /// <remarks/>
        Credit_Amount,
        
        /// <remarks/>
        VAT_Amount,
        
        /// <remarks/>
        VAT_Difference,
        
        /// <remarks/>
        Bal_VAT_Amount,
        
        /// <remarks/>
        Bal_VAT_Difference,
        
        /// <remarks/>
        Bal_Account_Type,
        
        /// <remarks/>
        Bal_Account_No,
        
        /// <remarks/>
        Bal_Gen_Posting_Type,
        
        /// <remarks/>
        Bal_Gen_Bus_Posting_Group,
        
        /// <remarks/>
        Bal_Gen_Prod_Posting_Group,
        
        /// <remarks/>
        Deferral_Code,
        
        /// <remarks/>
        Bal_VAT_Bus_Posting_Group,
        
        /// <remarks/>
        Bal_VAT_Prod_Posting_Group,
        
        /// <remarks/>
        Bill_to_Pay_to_No,
        
        /// <remarks/>
        Ship_to_Order_Address_Code,
        
        /// <remarks/>
        Shortcut_Dimension_1_Code,
        
        /// <remarks/>
        Shortcut_Dimension_2_Code,
        
        /// <remarks/>
        ShortcutDimCode_x005B_3_x005D_,
        
        /// <remarks/>
        ShortcutDimCode_x005B_4_x005D_,
        
        /// <remarks/>
        ShortcutDimCode_x005B_5_x005D_,
        
        /// <remarks/>
        ShortcutDimCode_x005B_6_x005D_,
        
        /// <remarks/>
        ShortcutDimCode_x005B_7_x005D_,
        
        /// <remarks/>
        ShortcutDimCode_x005B_8_x005D_,
        
        /// <remarks/>
        Payment_Terms_Code,
        
        /// <remarks/>
        Applied_Automatically,
        
        /// <remarks/>
        Applied,
        
        /// <remarks/>
        Applies_to_Doc_Type,
        
        /// <remarks/>
        Applies_to_Doc_No,
        
        /// <remarks/>
        Applies_to_ID,
        
        /// <remarks/>
        On_Hold,
        
        /// <remarks/>
        Bank_Payment_Type,
        
        /// <remarks/>
        Reason_Code,
        
        /// <remarks/>
        Comment,
        
        /// <remarks/>
        Direct_Debit_Mandate_ID,
        
        /// <remarks/>
        AccName,
        
        /// <remarks/>
        BalAccName,
        
        /// <remarks/>
        Balance,
        
        /// <remarks/>
        TotalBalance,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ReadByRecIdCompletedEventHandler(object sender, ReadByRecIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadByRecIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadByRecIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GeneralJournalService Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GeneralJournalService)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ReadMultipleCompletedEventHandler(object sender, ReadMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GeneralJournalService[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GeneralJournalService[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void IsUpdatedCompletedEventHandler(object sender, IsUpdatedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsUpdatedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsUpdatedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetRecIdFromKeyCompletedEventHandler(object sender, GetRecIdFromKeyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRecIdFromKeyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRecIdFromKeyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void CreateCompletedEventHandler(object sender, CreateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GeneralJournalService GeneralJournalService {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GeneralJournalService)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void CreateMultipleCompletedEventHandler(object sender, CreateMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GeneralJournalService[] GeneralJournalService_List {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GeneralJournalService[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void UpdateCompletedEventHandler(object sender, UpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GeneralJournalService GeneralJournalService {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GeneralJournalService)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void UpdateMultipleCompletedEventHandler(object sender, UpdateMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GeneralJournalService[] GeneralJournalService_List {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GeneralJournalService[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void DeleteCompletedEventHandler(object sender, DeleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591